#Base Image
FROM centos

#Maintainer
MAINTAINER shundong.zhao shundong.zhao@linuxhot.com

#Run
RUN rpm -ivh https://mirrors.aliyun.com/epel/epel-release-latest-7.noarch.rpm
RUN yum install -y wget sudo git tree net-tools && yum clean all
